### ISSUE TITLE
what are those values in face_model.txt?

### ISSUE THREAD

**Issue by LazyKai** [xucong-zhang/ETH-XGaze#10]
Hi, I don't quite understand what are those values in face_model.txt? Is there any difference between it and landmarks?

**Comment by xucong-zhang** [comment]
Hi, the values in face_model.txt are generic 3D facial landmarks that are pre-defined. We fit it to the detected landmark to get the 3D head pose.

**Comment by LazyKai** [comment]
Got it, thanks:)

**Comment by alantim** [comment]
Is there any documentation available regarding what body part corresponds to each landmark in the face_model.txt file, and the source of it?
