### ISSUE TITLE
Is gc the coordinate of target or calulated vector

### ISSUE THREAD

**Issue by LazyKai** [xucong-zhang/ETH-XGaze#11]
**gc_normalized = gc - face_center  # gaze vector**
I am not sure whether **gc** is the coordinate of target based on camera coordinate system or already calculated based on head coordinate system? And why doing this step?
please explain this, thanks!

**Comment by xucong-zhang** [comment]
Hi,

gc is the gaze point in the camera coordinate system. In other words. gc is the gaze point on the screen, and is converted to the camera coordinate system. gc_normalized is the real gaze vector.

**Comment by LazyKai** [comment]
Got it,thanks a lot!!!
