### ISSUE TITLE
Calibrating gaze vector to Screen point ?

### ISSUE THREAD

**Issue by ShreshthSaxena** [xucong-zhang/ETH-XGaze#12]
I'm trying to map the **pred_gaze_np**  output to the 2D screen point. Is this something already implemented ? If not can you please help me with what approach should be followed. 
I tried a simple polynomial regression from the vector to screen points and the results are decent but I'm wondering if there's a better approach.

**Comment by gv237-07** [comment]
Hi. Did you manage to figure it out please?

**Comment by ShreshthSaxena** [comment]
hey, yes I did... although [this](http://phi-ai.org/GazeHub/) came out recently and it's really well documented here.

**Comment by gv237-07** [comment]
Thank you very much

**Comment by gkagkos** [comment]
@ShreshthSaxena @gv237-07 hey, I am also having troubles to do that and [the link you have shared](http://phi-ai.buaa.edu.cn/GazeHub/index.jsp) is down. Could you let me know what process you followed and how did you get the gaze vector from screen point? Thanks again!
