### ISSUE TITLE
How to crop eye in the pre-processed datasets

### ISSUE THREAD

**Issue by senfu** [xucong-zhang/ETH-XGaze#18]
Hello, I downloaded the 224x224 pre-processed dataset but found that only normalized face images are provided. Is there any way to extract cropped eyes? Since I need eye patches for my model. Thanks!

**Comment by err-or** [comment]
Hi, did you find a way to get eye images from the preprocessed dataset?

**Comment by vuthede** [comment]
please follow that. 
https://github.com/xucong-zhang/ETH-XGaze/issues/17

**Comment by senfu** [comment]
Thank you very much. It helps me a lot.
