### ISSUE TITLE
about the pre-trained model

### ISSUE THREAD

**Issue by ZERO-SPACE-X** [xucong-zhang/ETH-XGaze#2]
Hi Xucong,

Excellent work on the ETH XGaze! Now I have meet an issue about the pre-trained model. I have download the model,but it can`t  uncompress. I don`t know whether there has something wrong with the source file.
Looking forward to your reply!

Best,
LiuGang

**Comment by xucong-zhang** [comment]
Hi LiuGang,

The pre-trained Pytorch model does not need to be uncompressed. It can be directly loaded. Please refer to the demo.py code for details.

Best,
Xucong

**Comment by ZERO-SPACE-X** [comment]
Thanks a lot.
