### ISSUE TITLE
Datasets Request Download

### ISSUE THREAD

**Issue by Fortogether** [xucong-zhang/ETH-XGaze#27]
Hi, I am a Master's degree student and I have made a request for the download service for this dataset 2 months ago. I have filled all the required information at that time but till now there is no response, can you please send me the download url of the dataset or some response to my mailbox, thank you very much.

**Comment by Fortogether** [comment]
My email is 20211083510920@buu.edu.cn

**Comment by xucong-zhang** [comment]
Hi,

Please do not write your email in public. I deleted the message with your email. I checked that your registration that was not completed. I will write you an email about it.

Regards,
Xucong
