### ISSUE TITLE
dataset download issues

### ISSUE THREAD

**Issue by JieShare** [xucong-zhang/ETH-XGaze#28]
Hi,
Sorry to bother you, I am an algorithm leader of a technology company in Shanghai
I want to download the dataset for researching and submitted the registration on the website according to the guidelines.
But i haven't received the download link.
My e-mail is [gongjiajie@iauto.com], could you please send me the download link? I have submitted the application.
Thanks for your great work and help!

**Comment by xucong-zhang** [comment]
Hi,

Thank you for your interest in downloading the dataset. Unfortunately, the GitHub repository is not a place to discuss the dataset download. I have to delete this issue. Please check your registration information.

Best regards,
Xucong
