### ISSUE TITLE
Full dataset with raw face images release time

### ISSUE THREAD

**Issue by xjcvip007** [xucong-zhang/ETH-XGaze#3]
Thank you for your amazing job~ One question, when will you release full dataset with raw face images?

**Comment by xucong-zhang** [comment]
Hi, thanks for your interest in our work. I am very sorry about the delay in releasing the full dataset. We already got the download server, but still waiting for someone to set up the website for downloading. I will pork them again and aim to release the full dataset before Christmas. Thank you for your patient.

**Comment by xjcvip007** [comment]
Thanks for your quick reply~

**Comment by xjcvip007** [comment]
Hi, does the data release time needed to be delayed?

**Comment by raijinspecial** [comment]
I am also interested in the full dataset, thanks for this excellent work.

**Comment by xucong-zhang** [comment]
Hi, @xjcvip007 @raijinspecial Thank you for your patient. We prepared the raw data and now we are doing the final internal test on it. I believe we will send emails to all people registered the dataset download within this week. I am sorry for keeping you wait so long.

**Comment by xjcvip007** [comment]
@xucong-zhang I am glad to receive your reply~

**Comment by xucong-zhang** [comment]
Hi @xjcvip007 @raijinspecial , the raw dataset is available now. You should already receive my email if you registered before. Please let me know by email if you already registered but did not receive my email about the raw data.

**Comment by xjcvip007** [comment]
Thanks for your amazing work again!
