### ISSUE TITLE
Syntax Error in main.py L23

### ISSUE THREAD

**Issue by sohams25** [xucong-zhang/ETH-XGaze#37]
Hey there,

I was trying to train the baseline model on dataset and noticed that there's a small syntax error.
In [L23](https://github.com/xucong-zhang/ETH-XGaze/blob/master/main.py#L23), there should be comma after `is_shuffle=True` or else it throws this [error](https://pastebin.com/EnZCHiLM).

**Comment by xucong-zhang** [comment]
Hi, thank you very much for pointing it out! Much appreciated. I corrected the mistake.

**Comment by sohams25** [comment]
Hey, thank you for considering the suggestion =)
I also wanted to tell you that I have dropped a mail to you. Can you please check it, when you're free?
